<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>

    <PackageId>Sisha.CleanArchitecture.Minimal</PackageId>
    <Version>1.0.0</Version>

    <Authors>Sisha.ir</Authors>

    <PackageType>Template</PackageType>

    <Title>Sisha Clean Architecture Minimal Template</Title>
    <Description>Minimal ASP.NET Core Clean Architecture solution template.</Description>

    <PackageTags>dotnet;template;clean-architecture;aspnetcore</PackageTags>

    <RepositoryUrl>https://github.com/Mansarix/sisha_minimal_clean_architecture</RepositoryUrl>

    <PackageLicenseExpression>MIT</PackageLicenseExpression>

    <IncludeContentInPack>true</IncludeContentInPack>
    <IncludeBuildOutput>false</IncludeBuildOutput>

    <ContentTargetFolders>content</ContentTargetFolders>

    <NoBuild>true</NoBuild>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="**\*" Exclude="bin\**;obj\**;.git\**;.vs\**" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>

</Project>
